import React, { useRef } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Platform } from 'react-native';
import { Share2, Users, Download, Calendar, Clock, FileText, Smartphone } from 'lucide-react-native';
import ViewShot, { captureRef } from 'react-native-view-shot';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { glassStyles, GLASS_COLORS } from '../theme/glass';

interface ReportViewProps {
  counts: { man: number; woman: number; child: number };
  startTime: Date;
  endTime: Date;
  onReset: () => void;
}

export const ReportView: React.FC<ReportViewProps> = ({ counts, startTime, endTime, onReset }) => {
  const reportRef = useRef<View>(null);
  const total = counts.man + counts.woman + counts.child;
  const duration = Math.floor((endTime.getTime() - startTime.getTime()) / 1000);

  const exportAsImage = async () => {
    try {
      const uri = await captureRef(reportRef, {
        format: 'png',
        quality: 0.9,
      });
      await Sharing.shareAsync(uri);
    } catch (err) {
      console.error('Export PNG failed:', err);
    }
  };

  const exportAsPDF = async () => {
    try {
      const html = `
        <html>
          <body style="font-family: sans-serif; padding: 40px; color: #1e293b;">
            <h1 style="border-bottom: 2px solid #0ea5e9; padding-bottom: 10px;">Human Counter Report</h1>
            <p><strong>Date:</strong> ${startTime.toLocaleDateString()}</p>
            <p><strong>Duration:</strong> ${duration} seconds</p>
            <hr />
            <h2>Statistics</h2>
            <ul>
              <li>Men: ${counts.man}</li>
              <li>Women: ${counts.woman}</li>
              <li>Children: ${counts.child}</li>
            </ul>
            <p style="font-size: 24px;"><strong>Total: ${total}</strong></p>
            <hr />
            <p style="color: #94a3b8; font-size: 12px;">Generated by Human Counter Mobile AI</p>
          </body>
        </html>
      `;
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri);
    } catch (err) {
      console.error('Export PDF failed:', err);
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.scrollContent}>
      <ViewShot ref={reportRef} options={{ format: 'png', quality: 0.9 }} style={styles.reportContainer}>
        <View style={[glassStyles.container, styles.mainCard]}>
          <View style={styles.header}>
            <View>
              <Text style={styles.title}>REPORT</Text>
              <View style={styles.meta}>
                <Calendar size={12} color={GLASS_COLORS.muted} />
                <Text style={styles.metaText}>{startTime.toLocaleDateString()}</Text>
                <Clock size={12} color={GLASS_COLORS.muted} style={{ marginLeft: 8 }} />
                <Text style={styles.metaText}>{duration}s</Text>
              </View>
            </View>
            <View style={glassStyles.darkCard}>
              <Users size={24} color="white" />
            </View>
          </View>

          <View style={styles.statGrid}>
            <StatItem label="MEN" value={counts.man} color={GLASS_COLORS.primary} />
            <StatItem label="WOMEN" value={counts.woman} color={GLASS_COLORS.secondary} />
            <StatItem label="KIDS" value={counts.child} color={GLASS_COLORS.accent} />
          </View>

          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>TOTAL FLOW</Text>
            <Text style={styles.totalValue}>{total}</Text>
          </View>
        </View>
      </ViewShot>

      <View style={styles.actions}>
        <ActionButton 
          icon={<Share2 size={20} color="white" />} 
          label="SHARE PNG" 
          onPress={exportAsImage} 
          color="#10b981" 
        />
        <ActionButton 
          icon={<FileText size={20} color="white" />} 
          label="EXPORT PDF" 
          onPress={exportAsPDF} 
          color="#3b82f6" 
        />
        <TouchableOpacity style={styles.resetButton} onPress={onReset}>
          <Text style={styles.resetText}>NEW SCAN</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
};

const StatItem: React.FC<{ label: string; value: number; color: string }> = ({ label, value, color }) => (
  <View style={styles.statItem}>
    <View style={[styles.statBadge, { backgroundColor: color }]}>
      <Text style={styles.statValue}>{value}</Text>
    </View>
    <Text style={styles.statLabel}>{label}</Text>
  </View>
);

const ActionButton: React.FC<{ icon: React.ReactNode; label: string; onPress: () => void; color: string }> = ({ icon, label, onPress, color }) => (
  <TouchableOpacity style={[styles.actionButton, { backgroundColor: color }]} onPress={onPress}>
    {icon}
    <Text style={styles.actionLabel}>{label}</Text>
  </TouchableOpacity>
);

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollContent: { padding: 20, paddingBottom: 60 },
  reportContainer: { backgroundColor: '#f8fafc', borderRadius: 24, padding: 10 },
  mainCard: { elevation: 5 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 32 },
  title: { fontSize: 32, fontWeight: '900', color: GLASS_COLORS.text, letterSpacing: -1 },
  meta: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
  metaText: { fontSize: 10, fontWeight: '700', color: GLASS_COLORS.muted, marginLeft: 4, letterSpacing: 1 },
  statGrid: { flexDirection: 'row', justifyContent: 'space-around', marginBottom: 40 },
  statItem: { alignItems: 'center' },
  statBadge: { width: 56, height: 56, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginBottom: 8, elevation: 3 },
  statValue: { fontSize: 20, fontWeight: '900', color: 'white' },
  statLabel: { fontSize: 8, fontWeight: '800', color: GLASS_COLORS.muted, letterSpacing: 1 },
  totalRow: { backgroundColor: '#f1f5f9', padding: 20, borderRadius: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  totalLabel: { fontSize: 12, fontWeight: '900', color: '#64748b', letterSpacing: 2 },
  totalValue: { fontSize: 24, fontWeight: '900', color: GLASS_COLORS.text },
  actions: { marginTop: 32, gap: 12 },
  actionButton: { height: 64, borderRadius: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 12, elevation: 4 },
  actionLabel: { color: 'white', fontWeight: '900', fontSize: 14, letterSpacing: 1 },
  resetButton: { height: 60, borderRadius: 20, borderWidth: 2, borderColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  resetText: { fontWeight: '900', color: '#64748b', letterSpacing: 2 },
});
